### PR TITLE
Fix: wrong invalid url warnings

### LINKED ISSUE #11983: Wrong "invalid URL" warning
### URL

https://www.openstreetmap.org/relation/8246670/

### How to reproduce the issue?

1. Edit the relation https://www.openstreetmap.org/relation/8246670/ in iD
2. Note that there's a warning that the relation has an invalid URL, the information text telling that URLs must being with http:// or https://
3. Also note that the URL does indeed begin with https:// (https://www.rando92.fr/randonner/itinéraires/), and the warning is therefore wrong

### Screenshot(s) or anything else?

Image

Image

The bug seems to be triggered by the accented letter "é" in the URL.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.39.0-dev

### Which browsers are you seeing this problem on?

Firefox

### PR DESCRIPTION
**Pull request by bhavyaKhatri2703**
Fixes #11983

Removes the `link.href.includes(url)` check which falsely flagged valid URLs containing accented characters, since `new URL()` normalizes both before comparison. Also handles the case for Upper case letters.
Fix suggested by @k-yle in #11985.

Added tests for accented characters, IDN domains, and uppercase domains (as added by @tyrasd  in 6adfc8c).

### CODE REVIEW

**Review by k-yle — DISMISSED** [review]
Previous discussion is at #11985. 👍 from me, since this fixes the false-positives.

@1ec5 and @hlfan, can you think of any false-negatives that this might cause?

**Comment by hlfan** [comment]
Yes, see #12036 😅

But checking for the url schema would probably be enough in that case.

File: modules/validations/invalid_format.js [hunk 1]
```diff
@@ -29,9 +29,8 @@ export function validationFormatting() {
 
         function isValidURL(url, strict = false) {
             try {
-                // First try strict WHATWG parsing
-                const link = new URL(url);
-                return link.href.includes(url);
+                new URL(url); // eslint-disable-line no-new
+                return true;
```
Comment (k-yle) [inline modules/validations/invalid_format.js]: okay, so based on https://github.com/openstreetmap/iD/pull/12030#issuecomment-4081574025 we'll need something like this:

```suggestion
                const link = new URL(url);
                return link.protocol.startsWith('http');
```

Comment (bhavyaKhatri2703) [reply modules/validations/invalid_format.js]: > okay, so based on [#12030 (comment)](https://github.com/openstreetmap/iD/pull/12030#issuecomment-4081574025) we'll need something like this:

yeah this passes the test in #12036

Comment (hlfan) [reply modules/validations/invalid_format.js]: Then I'd only change the return statement and leave the upper two lines as they are.

Comment (bhavyaKhatri2703) [reply modules/validations/invalid_format.js]: merged the #12036 test and made the changes

File: modules/validations/invalid_format.js [hunk 2]
```diff
@@ -29,9 +29,8 @@ export function validationFormatting() {
 
         function isValidURL(url, strict = false) {
             try {
-                // First try strict WHATWG parsing
```
Comment (hlfan) [inline modules/validations/invalid_format.js:32]: Is this comment really that unnecessary?

Comment (bhavyaKhatri2703) [reply modules/validations/invalid_format.js:32]: well i guess we can keep it. although its a very obvious comment. But yeah ill revert.

**Review by hlfan — COMMENTED** [review]
ICYMI I can't approve this, but I'd've put this into 2.39

**Review by k-yle — APPROVED** [review]

**Review by tyrasd — APPROVED** [review]
