### PR TITLE
fix: correct duplicate `parking:left:capacity` in osmSummableTags

### LINKED ISSUE #11819: Fix typo: `parking:left:capacity` duplicated in osmSummableTags, missing `parking:right:capacity`
### URL

_No response_

### How to reproduce the issue?

1. Open [modules/osm/tags.js] and navigate to lines 387-392
2. Observe the `osmSummableTags` Set definition:
   ```javascript
   export var osmSummableTags = new Set([
       'step_count',
       'parking:both:capacity',
       'parking:left:capacity',
       'parking:left:capacity'  // <-- Duplicate!
   ]);

<img width="740" height="235" alt="Image" src="https://github.com/user-attachments/assets/1a630b43-f1b8-414a-a369-b9028116b7b1" />


### Screenshot(s) or anything else?

_No response_

### Which deployed environments do you see the issue in?

_No response_

### What version numbers does this issue effect?

_No response_

### Which browsers are you seeing this problem on?

_No response_

### PR DESCRIPTION
**Pull request by JaiswalShivang**
fixes #11819 

## Summary
Fixes a typo in [modules/osm/tags.js] where `parking:left:capacity` was duplicated instead of including `parking:right:capacity`.

## Problem
The `osmSummableTags` Set incorrectly contained:
```javascript
export var osmSummableTags = new Set([
    'step_count',
    'parking:both:capacity',
    'parking:left:capacity',
    'parking:left:capacity'  // <-- Duplicate!
]);
## Previously
<img width="635" height="227" alt="image" src="https://github.com/user-attachments/assets/17fb218a-6655-4c79-897f-1db0e73be406" />
## After Updation
<img width="576" height="220" alt="image" src="https://github.com/user-attachments/assets/d6a7eeac-c9bc-45e8-849b-39e9bb495b19" />

### CODE REVIEW

**Comment by tordans** [comment]
Please add a changelog entry similar to how it was done in the last PRs.

**Comment by JaiswalShivang** [comment]
@tordans I have added the details in changelog.md

**Comment by JaiswalShivang** [comment]
@1ec5 i have resolved the conflict kindly see the pr

File: modules/osm/tags.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ const uninterestingKeyRegex = /^(source(_ref)?|tiger):/;
  */
 export function osmIsInterestingTag(key) {
     if (uninterestingKeys.has(key)) return false;
-    if (uninterestingKeyRegex.test(key))  return false;
```
Comment (matkoniecz) [inline modules/osm/tags.js:33]: can you drop this reformatting?

Comment (JaiswalShivang) [reply modules/osm/tags.js:33]: yes i am dropping this

File: modules/osm/tags.js [hunk 2]
```diff
@@ -30,7 +30,7 @@ const uninterestingKeyRegex = /^(source(_ref)?|tiger):/;
...
+    if (uninterestingKeyRegex.test(key)) return false;
```
Comment (matkoniecz) [inline modules/osm/tags.js]: reformatting is still here, merging in master will not remove it

Comment (matkoniecz) [reply modules/osm/tags.js]: it is gone now, thanks

Comment (JaiswalShivang) [reply modules/osm/tags.js]: removed now

File: CHANGELOG.md [hunk 3]
```diff
@@ -92,8 +93,9 @@ _Breaking developer changes, which may affect downstream projects or sites that
 [@homersimpsons]: https://github.com/homersimpsons
 [@omsaraykar]: https://github.com/omsaraykar
 [@Kaushik4141]: https://github.com/Kaushik4141
-[@Kayd-06]: https://github.com/Kayd-06
 [@JaiswalShivang]: https://github.com/JaiswalShivang
+[#11819]: https://github.com/openstreetmap/iD/pull/11819
+[@Kayd-06]: https://github.com/Kayd-06
```
Comment (matkoniecz) [inline CHANGELOG.md:98]: it seems that `[#11819]: https://github.com/openstreetmap/iD/pull/11819` should be moved up to be in order with PRs

**Comment by matkoniecz** [comment]
And thanks for making this PR!

File: CHANGELOG.md (hunk 3 above)
Comment (JaiswalShivang) [reply CHANGELOG.md:98]: resolved

**Review by tyrasd — APPROVED** [review]
good catch, thanks!
