### PR TITLE
fix the raw tag editor broken and strange cursor behaviour

### LINKED ISSUE #9762: Tag raw editor is empty
As of 2.26 or 2.26.1 the raw tag editor list is empty:

empty tag list

You can add text to it, but it generally leads to broken tagging, as it won't preserve existing ones.

This happens on any selected element - existing, new, modified.

No errors in console.

Win 10 Enterprise x64, Firefox and Opera.

### LINKED ISSUE #9764: addr:housenumber is glitchy during typing
### URL

https://www.openstreetmap.org/edit#map=19/51.74659/20.77788

### How to reproduce the issue?

1. Select an address
2. Clear the house number field
3. Start typing at least 2 char long number: 123
4. Result is 231

### Screenshot(s) or anything else?

_No response_

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.26.1

### Which browsers are you seeing this problem on?

Chrome

### LINKED ISSUE #9767: Changeset comment dropdown does not work
### URL

_No response_

### How to reproduce the issue?

Clicking the changeset comment box produces a dropdown list of recent comments, but clicking those comments no longer works - the dropdown disappears but the comment box is still empty

### Screenshot(s) or anything else?

2023-07-13 09_52_06-OpenStreetMap — Mozilla Firefox

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app

### What version numbers does this issue effect?

2.26.1,2.27.0-dev

### Which browsers are you seeing this problem on?

Chrome, Firefox

### LINKED ISSUE #9773: Cannot select recent changeset comment
### URL

Anywhere

### How to reproduce the issue?

1. Make changes on OSM
2. Click save
3. Click the textbox where the changeset comment should go to see all the recent changeset comments you can select
4. Click on a changeset comment you'd like to select
5. The changeset comment did not get added to the textbox

### Screenshot(s) or anything else?

This is the area I'm talking about
image

Furthermore, the textbox was already supposed to be filled because I am doing a Maproulette challenge that auto fills the textbox. 
Also, whenever I type one character of the top suggestion, so in this case #, it will suggest the top comment and fill it in if I click tab.

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

iD 2.26.1

### Which browsers are you seeing this problem on?

Microsoft Edge

### LINKED ISSUE #9774: Text mode editing for Tags does not work with iD 2.26.1
### URL

_No response_

### How to reproduce the issue?

1. Switch the tag list to text mode
2. Select any object on the map
3. Observe the tag list contents

Nothing happens, i.e. it is empty (although it does accept input, but it still does not change with selection). This is a horrible regression introduced in 2.26.0 or 2.26.1, so much I'd prefer it rolled back until fixed, since it makes any work with tags extremely cumbersome. 

### Screenshot(s) or anything else?

TagsBox

### Which deployed environments do you see the issue in?

_No response_

### What version numbers does this issue effect?

2.26.1 (perhaps 2.26.0)

### Which browsers are you seeing this problem on?

Firefox

### LINKED ISSUE #9775: Issue with Tag Conversion and Auto-modification of Elements
### URL

No response

### How to reproduce the issue?

1. Convert a list of tags to text.
2. Observe that the tags within the list disappear and the original elements lose their attributes.
3. Copy the tag text.
4. Notice that certain elements in the viewport are automatically modified to match the copied tag without any editing being performed.

### Screenshot(s) or anything else?

Uploading id 2.26.1.mp4…

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.26.1

### Which browsers are you seeing this problem on?

Chrome

### PR DESCRIPTION
**Pull request by k-yle**
Closes #9762, Closes #9764, Closes #9767, Closes #9773, Closes #9775, Closes #9774

to test:
 - go to https://osm.org/edit
 - select any feature with tags
 - note how the raw tag editor works again

edit: this PR indirectly fixes another bug reported on the OSM-US slack, where the changeset comment dropdown doesn't work

### CODE REVIEW

File: modules/util/get_set_value.js [hunk 1]
```diff
@@ -32,11 +32,12 @@ export function utilGetSetValue(selection, value, shouldUpdate) {
         // see https://html.spec.whatwg.org/multipage/input.html#concept-input-apply
         const supportedTypes = ['text', 'search', 'url', 'tel', 'password'];
         return function() {
+            func.apply(this, arguments);
+
             if (!supportedTypes.includes(this.type)) {
                 return;
             }
             const cursor = { start: this.selectionStart, end: this.selectionEnd };
```
Comment (1ec5) [inline modules/util/get_set_value.js:32]: Based on the code that changed, these regressions were probably introduced in 14c752548d2899b7411fcc8480ce3e2784df1253 (related to #8769 and 2b64d703523a2856bd41b894dff9fcd5dc4bdc75). I believe the intention was for this line to memoize the cursor position before setting the value in order to restore that position afterwards. It needs to go to the very top of this function before the call to `apply()`.

**Review by 1ec5 — COMMENTED** [review]
Good catch, but this introduces another subtle regression that should hopefully be simple to avoid.

File: modules/util/get_set_value.js (hunk 1 above)
Comment (k-yle) [reply modules/util/get_set_value.js:32]: thanks, it seems like this bug was present even before this PR (#9764) 

I've reworked the logic now so it also fixes #9764. are there any specific cases that are still broken for you?

Comment (1ec5) [reply modules/util/get_set_value.js:32]: Sorry, I was a bit unclear. 14c752548d2899b7411fcc8480ce3e2784df1253 attempted to fix #9233 but barely avoided fixing #9764 while creating other regressions. As far as I can tell, these changes do fix both issues.

**Review by 1ec5 — APPROVED** [review]

File: modules/util/get_set_value.js [hunk 2]
```diff
@@ -49,5 +43,12 @@ export function utilGetSetValue(selection, value, shouldUpdate) {
         shouldUpdate = (a, b) => a !== b;
     }
 
+    // only certain input element types allow manipulating the cursor
+    // see https://html.spec.whatwg.org/multipage/input.html#concept-input-apply
+    const supportedTypes = ['text', 'search', 'url', 'tel', 'password'];
+    if (!supportedTypes.includes(this.type)) {
```
Comment (tyrasd) [inline modules/util/get_set_value.js:49]: This does not quite work as probably intended: `this` is here the global (`window`) object, and not the input element we'd want to check (d3's `selection.each' binds the `this` variable to the DOM element in the callback function).

So, in practice, this condition is always fulfilled, even for input element types which would support cursor manipulation. As it still fixes the textarea/raw tag editor bug, I think we can keep it for the moment (even though #9233 is now an issue again), but I'll see if I can fix this a little bit better. :blush:
