### PR TITLE
fix html rendering of KeepRight and ImproveOSM modules

### LINKED ISSUE #8928: 2.20.3 has broken display of KeepRight issues
### URL

https://www.openstreetmap.org/edit#map=21/33.98965/-84.27306

### How to reproduce the issue?

Click the link above, enable KeepRight overlay, look at the names and descriptions of issues. 

This release has broken them.

### Screenshot(s) or anything else?

image

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

_No response_

### PR DESCRIPTION
**Pull request by tyrasd**
closes #8928

### CODE REVIEW

File: modules/ui/keepRight_header.js [hunk 1]
```diff
@@ -10,13 +10,14 @@ export function uiKeepRightHeader() {
...
     let replacements = d.replacements || {};
-    replacements.default = unknown;  // special key `default` works as a fallback string
+    replacements.default = { html: unknown };  // special key `default` works as a fallback string
 
-    let title = t.html(`QA.keepRight.errorTypes.${itemType}.title`, replacements);
-    if (title === unknown) {
-      title = t.html(`QA.keepRight.errorTypes.${parentIssueType}.title`, replacements);
+    const title = t.html(`QA.keepRight.errorTypes.${itemType}.title`, replacements);
+    if (title !== unknown) {
+      return t.apply(`QA.keepRight.errorTypes.${itemType}.title`, replacements);
```
Comment (tyrasd) [inline modules/ui/keepRight_header.js:17]: this should have been `t.html` here :disappointed: (same also two lines below)
