### PR TITLE
Restore URL validation

### LINKED ISSUE #6831: Offer to fix missing http:// in website tag
A website tag without http:// is highlighted as an issue - it would be good if iD offered to "upgrade" or fix this by adding the protocol.

Also, you'll notice I had to scroll down to actually see the website field. Perhaps iD could move fields which are an issue higher up in the list, or even into the issues section just below the yellow box?
website

### LINKED ISSUE #11436: Warn the user if a `url` field has a malformed URL
`url` fields such as `website=*` should validate input so that the user knows if they’re entering data that isn’t usable. For example, a schemaless URL like `website=example.com` causes the OSM website to incorrectly link to a relative URL: openstreetmap/openstreetmap-website#6407. Although this is incorrect behavior, it’s a sign that some user-facing data consumers might experience similar problems.

#6494 added a validation warning for malformed URLs in `url` fields such as `website=*`, but 9ccace9022e6c6cb37ea8638fce05cbf26972d14 later commented it out. In the discussion in #6831, we found it redundant to the red border that Firefox applied to malformed input automatically. Unfortunately, no other browser applied that border automatically, and Firefox has removed it as of version 143. (That discussion got derailed by an infeasible idea to automatically upgrade URLs from HTTP to HTTPS.)

We could uncomment the URL validation code, in which case I’d recommend replacing the custom regular expression with code that simply checks if a URL can be constructed:

```js
try {
  entity.tags.website.split(';').map(v => new URL(v));
} catch (e) {
  issues.push(…);
}
```

Alternatively, we could restore the behavior that Firefox used to have, but in every browser, by adding some CSS for the [`:invalid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) pseudoclass.

/ref #8827

### PR DESCRIPTION
**Pull request by hlfan**
Continuing #11438 to close #11436 and resolve #6831.

### CODE REVIEW

File: modules/validations/invalid_format.js [hunk 1]
```diff
@@ -26,11 +27,28 @@ export function validationFormatting() {
...
 
-        /* see https://github.com/openstreetmap/iD/issues/6831#issuecomment-537121379
-        function isSchemePresent(url) {
-            var valid_scheme = /^https?:\/\//i;
-            return (!url || valid_scheme.test(url));
+        function isValidURL(url, strict = false) {
+            try {
+                // First try strict WHATWG parsing
+                const link = new URL(url);
+                return link.protocol === 'http:' || link.protocol === 'https:';
```
Comment (1ec5) [inline modules/validations/invalid_format.js]: I shouldn’t be surprised, but there are actually [a handful of (S)FTP website values](https://overpass-turbo.eu/s/2eAl) globally, mostly in New Zealand, and they actually make some sense. They’re pretty rare, but are they valid? Some browsers like Firefox have dropped native support for FTP in recent years, making it a less user-friendly option for `website=*`. (I could not find any Telnet or Gopher URLs, for what it’s worth.)

**Review by 1ec5 — COMMENTED** [review]
Can you summarize what’s changed since #11438, if anything?

**Comment by hlfan** [comment]
The biggest addition are the dynamic fixes, but I also flattened the issue creation logic a bit and added messages in core.yaml.

See [this diff](https://github.com/Ankitgkp/iD/compare/663e4919d1453b52f1c936b6dc922522a5ba5e1a..hlfan:iD:url-format).

File: modules/validations/invalid_format.js (hunk 1 above)
Comment (hlfan) [reply modules/validations/invalid_format.js]: That check was only intended to catch wikimedia_commons file prefixes, but the automatic insertion of slashes is the better option here.

**Review by 1ec5 — APPROVED** [review]
This addresses the feedback I had in #11438.
