### PR TITLE
NSI related fixes

### LINKED ISSUE #8615: 2.20.0 tag validation issue
When adding Internet access tags to a hotel brand:

Before
image

After
image

### LINKED ISSUE #8617: NSI shouldn't match on `old_name` tag
Issue raised on Slack: `old_name` is not a name tag worth matching.

### PR DESCRIPTION
**Pull request by bhousel**
closes #8615 - preserve tag values that can be toplevel tags unless it's the toplevel tag for the matched item
closes #8617 - don't consider `old_name` as a name for matching

### CODE REVIEW

File: modules/services/nsi.js [hunk 1]
```diff
@@ -349,6 +349,7 @@ function gatherNames(tags) {
   }
 
   function isNamelike(osmkey, which) {
+    if (osmkey === 'old_name') return false;
```
Comment (mbrzakovic) [inline modules/services/nsi.js:352]: Perhaps a small detail but it would be cleaner to include this to 'notNames' exception list

**Review by mbrzakovic — APPROVED** [review]

File: modules/services/nsi.js (hunk 1 above)
Comment (bhousel) [reply modules/services/nsi.js:352]: I thought about that but `notNames` is already a pretty gnarly regex and I didn't want to make it worse.
