### PR TITLE
remove taginfo suggestions for `name:*` tags

### LINKED ISSUE #10287: Don't suggest values from Taginfo for `name:xx` tags
### URL

_No response_

### How to reproduce the issue?

1. Create an element
2. Go to it's tags
3. Add `name:xx`
4. Switch to the value box
5. Start typing
6. (notice the suggestions below)

### Screenshot(s) or anything else?

image

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.29.0

### Which browsers are you seeing this problem on?

Firefox

### PR DESCRIPTION
**Pull request by draunger**
# Description:
## approach
i have used slice method which slice the key which are starting with name and checks the condition after slicing

## attached screenshot after the fix 
image

## before this fix 
image

 ## attached issue
 https://github.com/openstreetmap/iD/issues/10287

### CODE REVIEW

**Comment by Dimitar5555** [comment]
I've just did a quick test and it seems like you can add `name: true` to this list and it will catch all `name:xx` variants, without all of the extra code you added. It is likely using some sort of regex under the hood, but I haven't looked for it.

> https://github.com/openstreetmap/iD/blob/49492a0e06aef71f90e96ab3ed50098df0f4ce93/modules/services/taginfo.js#L196-L209

**Comment by draunger** [comment]
@Dimitar5555 i did this before but it does not working

**Comment by draunger** [comment]
@1ec5 please review my PR so that i can make changes

File: modules/services/taginfo.js [hunk 1]
```diff
@@ -222,7 +222,7 @@ export default {
         this.keys(params, function(err, data) {
             if (err) return;
             data.forEach(function(d) {
-                if (d.value === 'opening_hours') return;  // exception
+                if (d.value === 'opening_hours') return;  //exception
                 _popularKeys[d.value] = true;
```
Comment (1ec5) [inline modules/services/taginfo.js]: I was wondering how this service excludes `name`, since it isn’t explicitly listed in `_popularKeys`. It turns out that `name` happens to be one of the 100 most popular keys that we add to the `_popularKeys` here. (There’s some additional explanation at https://github.com/openstreetmap/iD/issues/7485#issuecomment-605681756 that I had forgotten.)

File: modules/services/taginfo.js [hunk 2]
```diff
@@ -289,7 +289,7 @@ export default {
     values: function(params, callback) {
         // Exclude popular keys from values lookups.. see #3955
         var key = params.key;
-        if (key && _popularKeys[key]) {
+        if (key && _popularKeys[key] || key.slice(0,4)==='name') {
```
Comment (1ec5) [inline modules/services/taginfo.js]: [`String.prototype.startsWith`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) is less error-prone than comparing a substring manually. A more thorough fix would catch any key if it’s just a localized version of any of the popular keys. A localized key looks like `baseKey:xy`, where _xy_ is a language code (not necessarily two characters long). I think what you’ve got is OK, but I’d recommend switching to `startsWith` and also requiring a colon, like `name:`, in case someone types in a key that doesn’t have it like [`name_disaster`](https://taginfo.openstreetmap.org/keys/name_disaster#overview) or [`name_base`](https://taginfo.openstreetmap.org/keys/name_base#overview).

**Review by 1ec5 — COMMENTED** [review]
Thanks for your patience. In addition to the following comments, please consider writing a unit test for the change. You can find tests related to this file at test/spec/services/taginfo.js.

File: modules/services/taginfo.js (hunk 2 above)
Comment (draunger) [reply modules/services/taginfo.js]: @1ec5 as you said that start with name: will cause to name that starting without colon  shows suggestion,  so do i change with this  key.slice(0,4)==='name'  to this =>  key.slice(0,5)==='name:'  ??

**Review by tyrasd — CHANGES_REQUESTED** [review]
In addition to what @1ec5 already suggested, I think it would be preferred if this would not be a hardcoded case inside an `if` statement deep inside the code, especially given that there is already a list of tags for this. For example, one might want to also add `loc_name:xx`, or `description:xx` to this. One possible solution would be to change `_popularKeys` from a dictionary to a (list of) regular expressions:

```
_popularKeys = [
    /^postal_code$/,
    …
    /^name:../
];

…

if (key && _popularKeys.some(regex => regex.test(key)) {
    …
```

As this should not be a performance bottleneck, the lost efficiency compared to the dictionary lookup should be negligible. What do you think?

File: modules/services/taginfo.js (hunk 2 above)
Comment (draunger) [reply modules/services/taginfo.js]: > [`String.prototype.startsWith`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) is less error-prone than comparing a substring manually. A more thorough fix would catch any key if it’s just a localized version of any of the popular keys. A localized key looks like `baseKey:xy`, where _xy_ is a language code (not necessarily two characters long). I think what you’ve got is OK, but I’d recommend switching to `startsWith` and also requiring a colon, like `name:`, in case someone types in a key that doesn’t have it like [`name_disaster`](https://taginfo.openstreetmap.org/keys/name_disaster#overview) or [`name_base`](https://taginfo.openstreetmap.org/keys/name_base#overview).

Now sir what I do :
1.can i just make the testcase for it and send PR for it and remaining thing should be the same??

**Comment by draunger** [comment]
hey @tyrasd i have done the commited the changes as you said means used regex ...

**Comment by draunger** [comment]
hey @tyrasd i think you are right so i have done changes as you said means used regex and write the test case regarding this :)

**Comment by draunger** [comment]
@1ec5 can you re review my this PR as I have made some changes as Martin sir suggest and also made a testcase for this issue :)
