### PR TITLE
Integrate indexeddb for history and prefs sync with server

### LINKED ISSUE #3239: Switch to async storage (i.e. indexdb instead of localstorage)
Currently synchronous localstorage is used, which is fine for most things apart from [saving history](https://github.com/openstreetmap/iD/blob/39c82af15891bc29f89502ed60a3498895a1353e/modules/core/history.js#L372) which can grow very large and causes significant slow-down, despite the being [debounced to 350ms](https://github.com/openstreetmap/iD/blob/f7e49e79f8a6e5e2be33bca17ddfb3b1f4a39c11/js/id/id.js#L349-L356).

This is most noticeable when editing/creating complex line/polygon features, which result in the history being large, and writes to localstorage taking significant time, locking up the browser every 350ms. iD quickly becomes unusable in this scenario. This can be solved by frequent committing, but it is not an ideal solution.

To avoid a larger re-factor which would necessitate making all storage calls async, perhaps the quickest/easiest solution would be to use async storage for only `history.save()`.

IndexedDB is the obvious choice. Any recommendations for a lightweight wrapper that gets around any IndexedDB bugs or lack of support on browsers currently supported by iD (looking at you, Safari)? We only need a wrapper that implements basic `get()` and `put()`.

### LINKED ISSUE #11160: Migrate history storage from localStorage to IndexedDB and add async preferences API
### Description

Currently, iD uses `localStorage` for session data which has a hard 5MB limit, causing data loss and failed saves during extended mapping sessions or when working with large datasets. This storage constraint forces users to frequently restart their sessions and lose work progress, significantly impacting the mapping experience for power users and complex editing workflows.

This issue proposes migrating to `IndexedDB` which provides `50-100MB+` storage capacity (50x+ increase), asynchronous non-blocking operations, and atomic transactions. The implementation will include automatic migration of existing `localStorage` data, graceful fallbacks, and a new `asyncPrefs API` alongside the existing synchronous interface to maintain backward compatibility while enabling future server synchronization capabilities.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Deeptanshu-sankhwar**
### Changes Made

• **Added IndexedDB storage** using `idb-keyval` library to replace localStorage for history data
• **Created `asyncPrefs` API** for asynchronous preference operations alongside existing `prefs`
• **Implemented `migrateHistoryData()`** to automatically migrate existing localStorage history to IndexedDB
• **Updated history module** to save/restore from IndexedDB instead of localStorage
• **Added test cases** for migration function and asyncPrefs functionality

### Dependencies
• Added `idb-keyval` for IndexedDB operations
• Added `fake-indexeddb` for testing

This enables better data persistence while maintaining backward compatibility.

migration_flowchart

### CODE REVIEW

File: modules/core/preferences.js [hunk 1]
```diff
@@ -1,5 +1,8 @@
 // https://github.com/openstreetmap/iD/issues/772
 // http://mathiasbynens.be/notes/localstorage-pattern#comment-9
```
Comment (tordans) [inline modules/core/preferences.js]: This commend might be outdated.

Comment (Deeptanshu-sankhwar) [reply modules/core/preferences.js]: Thanks for you pointing it out @tordans , shall I remove the comment from `preferences.js` then?

**Comment by Deeptanshu-sankhwar** [comment]
Closes #11160

**Comment by tyrasd** [comment]
I found one more comment (in [`context.js#L294`](
https://github.com/Deeptanshu-sankhwar/iD/blob/73b2981beabb749072fb8e143f2ef1fc46569dad/modules/core/context.js#L294)) which is now outdated, and could need an update:

```js
  // Debounce save, since it's a synchronous localStorage write,
  // and history changes can happen frequently (e.g. when dragging).
  context.debouncedSave = _debounce(context.save, 350);
```

I assume there is still merit to keep the debouncing logic on the history-saving function (`debouncedSave`), even though it's less of an issue after switching from localstorage to indexeddb. But perhaps we could reduce the debouncing time to something that is triggering slightly more frequently (e.g. like 100ms). Do you think that makes sense @Deeptanshu-sankhwar ?

File: modules/core/history.js [hunk 2]
```diff
@@ -355,6 +355,7 @@ export function coreHistory(context) {
                 _tree = coreTree(_stack[0].graph);
                 _checkpoints = {};
             }
+            _pausedGraph = null;
```
Comment (tyrasd) [inline modules/core/history.js:354]: This variable looks to be unused? What is/was its purpose?

File: modules/core/history.js [hunk 3]
```diff
@@ -652,20 +653,25 @@ export function coreHistory(context) {
             if (lock.locked() &&
                 // don't overwrite existing, unresolved changes
                 !_hasUnresolvedRestorableChanges) {
-                const success = prefs(getKey('saved_history'), history.toJSON() || null);
 
-                if (!success) dispatch.call('storage_error');
+                const historyData = history.toJSON();
+                if (historyData) {
+                    asyncPrefs.set(getKey('saved_history'), historyData);
+                    prefs(getKey('has_saved_history'), true);
```
Comment (tyrasd) [inline modules/core/history.js]: I'd say it would be more stable if this was only set after the async set is complete:

`asyncPrefs.set(…).then(() => prefs(…, true))`

File: modules/core/history.js [hunk 4]
```diff
@@ -652,20 +653,25 @@ export function coreHistory(context) {
...
-        // delete the history version saved in localStorage
+        // delete the history version saved in IndexedDB
         clearSaved: function() {
             context.debouncedSave.cancel();
             if (lock.locked()) {
                 _hasUnresolvedRestorableChanges = false;
-                prefs(getKey('saved_history'), null);
+
+                asyncPrefs.set(getKey('saved_history'), undefined);
+                prefs(getKey('has_saved_history'), null);
```
Comment (tyrasd) [inline modules/core/history.js]: see above

File: modules/core/preferences.js [hunk 5]
```diff
@@ -41,10 +45,57 @@ function corePreferences(k, v) {
...
 export { corePreferences as prefs };
+
+export const asyncPrefs = {
+  /** @param {string} key */
+  get(key) {
+    if (corePreferences(key)) {
+      const parsed = JSON.parse(corePreferences(key));
+      corePreferences(key, null);
+      return parsed;
+    }
```
Comment (tyrasd) [inline modules/core/preferences.js]: when/how is this code branch used?

File: modules/core/preferences.js [hunk 6]
```diff
@@ -41,10 +45,57 @@ function corePreferences(k, v) {
...
+
+    return get(key);
+  },
+  set,
+};
+
+export async function migrateHistoryData() {
+  const historyKeyPattern = /^iD_.*_saved_history$/;
```
Comment (tyrasd) [inline modules/core/preferences.js]: This looks unnecessarily complicated. the storage key for the history data is already known (`getKey('saved_history')`), so there's no need to do this with a regular expression. Or am I overlooking something?

File: test/spec/core/history.js [hunk 7]
```diff
@@ -571,4 +567,54 @@ describe('iD.coreHistory', function () {
             expect(history.difference().deleted().length).to.eql(1);
         });
     });
+
+    describe('#replaceLocalStorageWithIndexedDB', function() {
+        beforeEach(function() {
+            var FDBFactory = require('fake-indexeddb/lib/FDBFactory');
```
Comment (tyrasd) [inline test/spec/core/history.js]: please use `import …` syntax to load dependencies also in test files

File: test/spec_helpers.mts [hunk 8]
```diff
@@ -6,6 +6,12 @@ import 'happen';
 import fetchMock from 'fetch-mock';
 import envs from '../config/envs.mjs';
 
+// Setup global IndexedDB mock for all tests
```
Comment (tyrasd) [inline test/spec_helpers.mts]: what's the reason to go with this setup over fake-indexeddb's auto setup (`import "fake-indexeddb/auto";`)?

**Review by tyrasd — CHANGES_REQUESTED** [review]
Please rebase the PR on the current develop branch to solve the conflict in `package-lock.json`.

Also see some inline remarks below.

File: modules/core/history.js (hunk 2 above)
Comment (Deeptanshu-sankhwar) [reply modules/core/history.js:354]: Hello @tyrasd , `_pausedGraph` variable is used to temporarily store a graph state when change event dispatching is pause, I've set `_pausedGraph = null` in the `reset` function to ensure that any paused state is cleared when the history is reset

File: modules/core/history.js (hunk 3 above)
Comment (Deeptanshu-sankhwar) [reply modules/core/history.js]: I have chained setting the `has_saved_history`, inside the async call now

File: modules/core/history.js (hunk 4 above)
Comment (Deeptanshu-sankhwar) [reply modules/core/history.js]: made the same changes here

File: modules/core/preferences.js (hunk 5 above)
Comment (Deeptanshu-sankhwar) [reply modules/core/preferences.js]: this change was relating if in case the migration logic fails, but this appears to be very redundant instead, I have removed the redundant code from here, since `migrateHistoryData` function would take care of moving key, values from localstorage to indexeddb

File: modules/core/preferences.js (hunk 6 above)
Comment (Deeptanshu-sankhwar) [reply modules/core/preferences.js]: Thank you for pointing, I have use `saved_history` directly to get the history keys, instead of regex

File: test/spec_helpers.mts (hunk 8 above)
Comment (Deeptanshu-sankhwar) [reply test/spec_helpers.mts]: I wasn't aware of `fake-indexeddb/auto`, I have used it now directly instead of cherry picking modules from `fake-indexeddb`, it is very helpful to automatically setup mock implementation of IndexedDB

**Review by tyrasd — APPROVED** [review]
