### PR TITLE
fix `destination_sign` relations not updated when splitting a way

### LINKED ISSUE #9188: Splitting a 'to' member of destination_sign relations adds an extra 'to' member
### URL

_No response_

### How to reproduce the issue?

Just split a way that is a 'to' member of any destination_sign relation.
destination_sign relations can have exactly one 'to' member.
Splitting a 'from' member also adds extra 'from', not sure if that is a problem too.

### Screenshot(s) or anything else?

_No response_

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

### PR DESCRIPTION
**Pull request by k-yle**
Closes #9188

[`destination_sign`](https://osm.wiki/Relation:destination_sign) can use the `intersection` role instead of `via`. 

There are still valid cases `destination_sign` relations won't be split properly, such as if there is no `from` role. But this helps with the most common cases

### CODE REVIEW

**Review by tordans — COMMENTED** [review]
There are a few code comments that only reference the VIA now. Is there a way to update those without writing an essay on the topic? :)

File: test/spec/actions/split.js [hunk 1]
```diff
@@ -1674,7 +1676,7 @@ describe('iD.actionSplit', function () {
                     iD.osmRelation({id: 'r', tags: {type: type}, members: [
                         {id: '-', role: 'from', type: 'way'},
                         {id: '~', role: 'to', type: 'way'},
-                        {id: 'd', role: 'via', type: 'node'}
+                        {id: 'd', role: via, type: 'node'}
```
Comment (tordans) [inline test/spec/actions/split.js]: When reading the changes, I did not immediately get this. Maybe a different name like `viaKey` would make it more explicit? (Code editors will also help with proper tool tips and highlighting, though)

**Comment by k-yle** [comment]
> There are a few code comments that only reference the VIA now. Is there a way to update those without writing an essay on the topic? :)

good point, although I can't think of concise word that encompasses `via` and `intersection`. Something like `midpoint` is more verbose and possibly less obvious than `via`...

**Review by tyrasd — APPROVED** [review]
