### PR TITLE
Render edit menu to the over-map layer. Fixes #10495

### LINKED ISSUE #10495: Street level imagery: Viewer overlaps right click menu
### URL

_No response_

### How to reproduce the issue?

**Observed behaviour**
1. Enable street level imagery
2. Select an image to view
3. Create an object
4. Move the map manually so the object is above the street level imagery viewer [1]
5. Right click on the object
6. The right click / edit menu and associated hover tooltips are partially obscured by the street level imagery viewer

**Expected behaviour**
The right click / edit menu and tooltips are moved in front of the viewer.
Additionally the orientation of the menu could be changed to horizontal so it does not overlap the viewer.

Related #7368 

---

[1]; can be useful, as it is closer to the user's reading direction as well as being closer to the 'Tag this photo id on the currently selected map feature'.

### Screenshot(s) or anything else?

image

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.4

### Which browsers are you seeing this problem on?

Chrome

### PR DESCRIPTION
**Pull request by fahnestd**
This Fixes #10495 by rendering the menu to the `over-map` layer rather than the `supersurface`. I had to make a ref to `overMap` available which i'm not sure how to get around currently. If this is not ideal, please let me know if there are any tips on how to achieve this otherwise.

image

### CODE REVIEW

File: modules/ui/init.js [hunk 1]
```diff
@@ -665,13 +666,16 @@ export function uiInit(context) {
             .triggerType(triggerType)
             .operations(operations);
 
-        // render the menu
-        context.map().supersurface.call(_editMenu);
+        // render the menu onto the overmap
+        overMap
+            // .append('div')
+            // .attr('class', 'menu-topbar-offset')
```
Comment (tyrasd) [inline modules/ui/init.js]: please remove the commented out lines. :relaxed:

File: modules/ui/edit_menu.js [hunk 2]
```diff
@@ -226,7 +229,8 @@ export function uiEditMenu(context) {
         }
 
         var origin = geoVecAdd(anchorLoc, offset);
-
+        // adjusts for top menu height
+        origin[1] -= _verticalOffset;
```
Comment (tyrasd) [inline modules/ui/edit_menu.js]: instead of the hardcoded offset, we could instead read the rendered height of the toolbar like this:

```suggestion
        // adjusts for top menu height
        var _verticalOffset = parseFloat(utilGetDimensions(d3_select('.top-toolbar-wrap'))[1]);
        origin[1] -= _verticalOffset;
```

This would then automatically continue to work if the toolbar size would change in the future.

**Review by tyrasd — CHANGES_REQUESTED** [review]
Thank you, this PR looks quite good already.

It's fine to store a local reference to the `overMap` selection inside of a module.

Please see the two comments line below with some suggestions:

File: modules/ui/edit_menu.js (hunk 2 above)
Comment (fahnestd) [reply modules/ui/edit_menu.js]: Great! that's changed!

**Review by tyrasd — APPROVED** [review]

File: modules/ui/init.js [hunk 3]
```diff
@@ -665,13 +666,14 @@ export function uiInit(context) {
...
-        context.map().supersurface.call(_editMenu);
+        // render the menu onto the overmap
+        overMap
+            .call(_editMenu);
     };
 
     ui.closeEditMenu = function() {
         // remove any existing menu no matter how it was added
-        context.map().supersurface
+       overMap
```
Comment (tyrasd) [inline modules/ui/init.js]: to fix unit tests (where `closeEditMenu` might be classed without a properly initialized `overMap`):

```suggestion
        if (overMap !== undefined) {
            overMap.select('.edit-menu').remove();
        }
```
