### PR TITLE
Fix changeSet keys like hashtag being a suggestion for objects

### LINKED ISSUE #11625: iD suggests hashtags as a key on objects
### How to reproduce the issue?

iD will suggest _hashtags_ as a key on OSM objects even though this is a tag key that should be limited to changesets.

### Screenshot(s) or anything else?

Image

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.37.3

### Which browsers are you seeing this problem on?

Other (please specify) browser independent.

### PR DESCRIPTION
**Pull request by bhavyaKhatri2703**
added a new regex expression for excluding key names similar to _extraExcludedKeys. 
Not sure what else can be added to this expression.

Fixes #11625

### CODE REVIEW

File: modules/services/taginfo.js [hunk 1]
```diff
@@ -15,6 +15,8 @@ var _popularKeys = {};
 // these will be returned by keys(), but taginfo will not be queried for values() requests
 var _extraExcludedKeys = /^(postal_code|via|((int_|loc_|nat_|official_|old_|ref_|reg_|short_|full_|sorting_|alt_|artist_|long_|bridge:|tunnel:)?name(:left|:right)?(:[a-z]+)?))$/;
 
+var _extraExcludedKeyNames = /^(hashtag|hashtags)$/;
```
Comment (hlfan) [inline modules/services/taginfo.js]:
```suggestion
var _extraExcludedKeyNames = /^(hashtags?|created_by)$/;
```

File: modules/services/taginfo.js [hunk 2]
```diff
@@ -245,7 +247,7 @@ export default {
                 callback(err);
             } else {
                 var f = filterKeys(params.filter);
-                var result = d.data.filter(f).sort(sortKeys).map(valKey);
+                var result = d.data.filter(f).filter(function(d) { return !_extraExcludedKeyNames.test(d.key); }).sort(sortKeys).map(valKey);
```
Comment (hlfan) [inline modules/services/taginfo.js]:
```suggestion
                var result = d.data.filter(f).filter(d => !_extraExcludedKeyNames.test(d.key)).sort(sortKeys).map(valKey);
```

**Review by hlfan — COMMENTED** [review]
This looks good to me now.

**Comment by bhavyaKhatri2703** [comment]
am i allowed to tag someone for a review?

**Review by k-yle — APPROVED** [review]
